export const POINTS = [
  { value: "A", label: "Tricycle Area (Dorm)" },
  { value: "B", label: "B. Kanlaon" },
  { value: "C", label: "B. Madyaas" },
  { value: "D", label: "B. Apitong" },
  { value: "E", label: "B. Miagos" },
  { value: "F", label: "B. Gumamela" },
  { value: "G", label: "B. Lampirong" },
  { value: "H", label: "Waiting Shed" },
  { value: "I", label: "HSU" },
  { value: "J", label: "College of Management" },
  { value: "K", label: "Guard House" },
  { value: "L", label: "New Admin" },
  { value: "M", label: "CUB" },
  { value: "N", label: "CAS" },
  { value: "O", label: "CFOS" },
  { value: "P", label: "Bangs" },
  { value: "Q", label: "Hatchery" },
  { value: "R", label: "Box 1" },
  { value: "S", label: "Tricycle Area (Banwa)" },
];